/* eslint-disable max-lines */
module.exports = {
  parser: 'babel-eslint',
  env: {
    browser: true,
    es6: true,
    jest: true,
    node: true,
    worker: true,
  },
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly',
  },
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: 'module',
  },
  plugins: ['eslint-comments', 'import', 'jest', 'unicorn'],
  rules: {
    // -- incompatible or made redundant w/ prettier
    // 'array-bracket-newline': [2, { multiline: true }],
    // 'array-element-newline': [2, { multiline: true }],
    // 'function-paren-newline': [2, 'multiline'],
    // 'max-len': [1, { code: 80 }],
    // 'no-mixed-operators': 2,
    // 'object-curly-newline': [2, { multiline: true }],
    // 'operator-linebreak': [2, 'before'],
    // indent: [2, 2],

    'no-duplicate-imports': 2,
    'semi-spacing': [2, { after: true, before: false }],

    // -- eslint - errors
    'for-direction': 2,
    'getter-return': 2,
    'no-await-in-loop': 2,
    'no-class-assign': 2,
    'no-compare-neg-zero': 2,
    'no-cond-assign': [2, 'always'],
    'no-const-assign': 2,
    'no-constant-condition': 2,
    'no-control-regex': 2,
    'no-debugger': 2,
    'no-dupe-args': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 2,
    'no-empty': [2, { allowEmptyCatch: false }],
    'no-empty-character-class': 2,
    'no-extra-boolean-cast': 2,
    'no-extra-parens': [
      2,
      'all',
      {
        ignoreJSX: 'all',
        returnAssign: false,
        enforceForArrowConditionals: false,
        nestedBinaryExpressions: false,
        conditionalAssign: false,
      },
    ],
    'no-extra-semi': 2,
    'no-func-assign': 2,
    'no-inner-declarations': [2, 'both'],
    'no-invalid-regexp': 2,
    'no-irregular-whitespace': 2,
    'no-native-reassign': 2,
    'no-obj-calls': 2,
    'no-prototype-builtins': 0,
    'no-regex-spaces': 2,
    'no-sparse-arrays': 2,
    'no-template-curly-in-string': 2,
    'no-unexpected-multiline': 2,
    'no-unreachable': 2,
    'no-unsafe-finally': 2,
    'no-unsafe-negation': 2,
    'use-isnan': 2,
    'valid-jsdoc': 0,
    'valid-typeof': [2, { requireStringLiterals: true }],

    // -- eslint - best practice
    'accessor-pairs': [2, { setWithoutGet: true }],
    'array-callback-return': 2,
    'block-scoped-var': 0,
    'callback-return': 0,
    'class-methods-use-this': [
      2,
      { exceptMethods: ['render', 'shouldComponentUpdate'] },
    ],
    complexity: [2, 6],
    'consistent-return': 2,
    'constructor-super': 2,
    curly: [2, 'all'],
    'default-case': 2,
    'dot-location': [2, 'property'],
    'dot-notation': 2,
    eqeqeq: [2, 'always'],
    'guard-for-in': 2,
    'handle-callback-err': 0,
    'init-declarations': 0,
    'max-classes-per-file': 0,
    'no-alert': 2,
    'no-buffer-constructor': 2,
    'no-caller': 2,
    'no-case-declarations': 2,
    'no-catch-shadow': 0,
    'no-console': 2,
    'no-delete-var': 0,
    'no-div-regex': 2,
    'no-dupe-class-members': 2,
    'no-else-return': [2, { allowElseIf: false }],
    'no-empty-function': 1,
    'no-empty-pattern': 2,
    'no-eq-null': 2,
    'no-eval': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-extra-label': 0,
    'no-fallthrough': 2,
    'no-floating-decimal': 2,
    'no-global-assign': 2,
    'no-implicit-coercion': 2,
    'no-implicit-globals': 0,
    'no-implied-eval': 2,
    'no-invalid-this': 0,
    'no-iterator': 2,
    'no-label-var': 0,
    'no-labels': 2,
    'no-lone-blocks': 2,
    'no-loop-func': 2,
    'no-magic-numbers': 0,
    'no-mixed-requires': [2, { allowCall: false, grouping: true }],
    'no-multi-spaces': 2,
    'no-multi-str': 2,
    'no-new': 2,
    'no-new-func': 2,
    'no-new-require': 2,
    'no-new-symbol': 2,
    'no-new-wrappers': 2,
    'no-octal': 2,
    'no-octal-escape': 2,
    'no-param-reassign': [2, { props: false }],
    'no-path-concat': 2,
    'no-process-env': 2,
    'no-process-exit': 2,
    'no-proto': 2,
    'no-redeclare': 2,
    'no-return-assign': 2,
    'no-return-await': 2,
    'no-script-url': 2,
    'no-self-assign': 2,
    'no-self-compare': 2,
    'no-sequences': 2,
    'no-shadow': [2, { builtinGlobals: false, hoist: 'functions' }],
    'no-shadow-restricted-names': 2,
    'no-sync': 2,
    'no-this-before-super': 2,
    'no-throw-literal': 2,
    'no-undef': 2,
    'no-undef-init': 0,
    'no-undefined': 0,
    'no-unmodified-loop-condition': 2,
    'no-unused-expressions': [2, { allowTaggedTemplates: true }],
    'no-unused-labels': 0,
    'no-unused-vars': [
      2,
      {
        args: 'after-used',
        vars: 'all',
        caughtErrors: 'none',
        ignoreRestSiblings: true,
      },
    ],
    'no-use-before-define': 0,
    'no-useless-call': 2,
    'no-useless-catch': 2,
    'no-useless-concat': 2,
    'no-useless-escape': 2,
    'no-useless-return': 2,
    'no-var': 2,
    'no-void': 2,
    'no-warning-comments': 0,
    'no-with': 2,
    'prefer-promise-reject-errors': 2,
    radix: 0,
    'require-await': 0,
    strict: [2, 'never'],
    'wrap-iife': [2, 'inside', { functionPrototypeMethods: true }],
    yoda: [2, 'never'],
    // 'no-restricted-globals': [2, {}],
    // 'no-restricted-imports': [2, 'module-name'],
    // 'no-restricted-modules': [2, 'module-name'],
    // 'no-restricted-properties': [2, {}],

    // -- eslint - stylistic
    'array-bracket-spacing': [2, 'never'],
    'arrow-body-style': [
      2,
      'as-needed',
      { requireReturnForObjectLiteral: false },
    ],
    'arrow-parens': [2, 'always'],
    'arrow-spacing': [2, { after: true, before: true }],
    'block-spacing': [2, 'always'],
    'brace-style': [2, '1tbs', { allowSingleLine: false }],
    camelcase: [2, { properties: 'always' }],
    'capitalized-comments': 0,
    'comma-dangle': [2, 'always-multiline'],
    'comma-spacing': [2, { before: false, after: true }],
    'comma-style': [2, 'last'],
    'computed-property-spacing': [2, 'never'],
    'consistent-this': 0,
    'eol-last': [2, 'always'],
    'func-call-spacing': [2, 'never'],
    'func-name-matching': 2,
    'func-names': [2, 'always'],
    'func-style': [2, 'declaration', { allowArrowFunctions: false }],
    'generator-star-spacing': [2, { after: true, before: false }],
    'implicit-arrow-linebreak': 0,
    'jsx-quotes': [2, 'prefer-double'],
    'key-spacing': [
      2,
      { beforeColon: false, afterColon: true, mode: 'strict' },
    ],
    'keyword-spacing': [2, { before: true, after: true }],
    'line-comment-position': [2, 'above'],
    'linebreak-style': [2, 'unix'],
    'lines-around-comment': [
      2,
      {
        beforeBlockComment: true,
        afterBlockComment: true,
        beforeLineComment: false,
        afterLineComment: false,
        allowBlockStart: true,
        allowBlockEnd: false,
        allowClassStart: true,
        allowClassEnd: false,
        allowObjectStart: true,
        allowObjectEnd: false,
        allowArrayStart: true,
        allowArrayEnd: false,
        ignorePattern: 'jest-environment|flow|jsdom',
      },
    ],
    'lines-between-class-members': [
      2,
      'always',
      { exceptAfterSingleLine: false },
    ],
    'max-depth': [2, 4],
    'max-lines': [2, 200],
    'max-nested-callbacks': [2, 4],
    'max-params': [2, 4],
    'max-statements': [2, 20, { ignoreTopLevelFunctions: false }],
    'max-statements-per-line': [2, { max: 1 }],
    'multiline-comment-style': [2, 'separate-lines'],
    'multiline-ternary': [2, 'always-multiline'],
    'new-cap': [
      2,
      {
        capIsNewExceptions: [],
      },
    ],
    'new-parens': 2,
    'newline-per-chained-call': 0,
    'no-array-constructor': 2,
    'no-bitwise': 2,
    'no-confusing-arrow': [2, { allowParens: true }],
    'no-continue': 2,
    'no-inline-comments': 0,
    'no-lonely-if': 2,
    'no-mixed-spaces-and-tabs': 2,
    'no-multi-assign': 2,
    'no-multiple-empty-lines': [2, { max: 1 }],
    'no-negated-condition': 2,
    'no-nested-ternary': 2,
    'no-new-object': 2,
    'no-plusplus': 0,
    'no-tabs': 2,
    'no-ternary': 0,
    'no-trailing-spaces': [2, { skipBlankLines: false, ignoreComments: false }],
    'no-underscore-dangle': [2, { allow: [] }],
    'no-unneeded-ternary': 2,
    'no-useless-computed-key': 2,
    'no-useless-constructor': 2,
    'no-useless-rename': 2,
    'no-whitespace-before-property': 2,
    'nonblock-statement-body-position': 0,
    'object-curly-spacing': [2, 'always'],
    'object-property-newline': [2, { allowAllPropertiesOnSameLine: true }],
    'object-shorthand': [2, 'always', { avoidExplicitReturnArrows: false }],
    'one-var': [2, 'never'],
    'one-var-declaration-per-line': 0,
    'operator-assignment': [2, 'always'],
    'padded-blocks': [2, 'never', { allowSingleLineBlocks: false }],
    'padding-line-between-statements': [
      2,
      {
        blankLine: 'always',
        prev: ['multiline-block-like'],
        next: ['expression', 'const', 'let'],
      },
      { blankLine: 'always', prev: ['block-like'], next: 'block-like' },
      { blankLine: 'always', prev: ['const', 'let', 'expression'], next: '*' },
      { blankLine: 'any', prev: 'expression', next: 'expression' },
      { blankLine: 'any', prev: ['const', 'let'], next: ['const', 'let'] },
      { blankLine: 'always', prev: '*', next: 'return' },
    ],
    'prefer-arrow-callback': [
      2,
      { allowNamedFunctions: false, allowUnboundThis: true },
    ],
    'prefer-const': [
      2,
      { destructuring: 'all', ignoreReadBeforeAssign: false },
    ],
    'prefer-destructuring': [
      2,
      { array: true, object: false },
      { enforceForRenamedProperties: false },
    ],
    'prefer-named-capture-group': 2,
    'prefer-numeric-literals': 2,
    'prefer-object-spread': 2,
    'prefer-rest-params': 2,
    'prefer-spread': 2,
    'prefer-template': 2,
    'quote-props': [2, 'as-needed'],
    quotes: [2, 'single', { avoidEscape: true }],
    'require-jsdoc': 0,
    'require-yield': 2,
    'rest-spread-spacing': [2, 'never'],
    semi: [2, 'always'],
    'semi-style': [2, 'last'],
    'sort-imports': 0,
    'sort-keys': 0,
    'sort-vars': 0,
    'space-before-blocks': [2, 'always'],
    'space-before-function-paren': [
      2,
      { anonymous: 'never', named: 'never', asyncArrow: 'always' },
    ],
    'space-in-parens': [2, 'never'],
    'space-infix-ops': 2,
    'space-unary-ops': 2,
    'spaced-comment': [2, 'always'],
    'switch-colon-spacing': [2, { after: true, before: false }],
    'symbol-description': 2,
    'template-curly-spacing': [2, 'never'],
    'template-tag-spacing': [2, 'never'],
    'unicode-bom': [2, 'never'],
    'wrap-regex': 0,
    'yield-star-spacing': [2, { after: true, before: false }],

    // eslint-plugin-import
    'import/default': 2,
    'import/dynamic-import-chunkname': 2,
    'import/export': 2,
    'import/exports-last': 0,
    'import/extensions': [
      2,
      { json: 'never', js: 'never', png: 'always', svg: 'always' },
    ],
    'import/first': 2,
    'import/group-exports': 0,
    'import/max-dependencies': 0,
    'import/named': 2,
    'import/namespace': 2,
    'import/newline-after-import': 2,
    'import/no-absolute-path': 2,
    'import/no-amd': 2,
    'import/no-anonymous-default-export': 0,
    'import/no-commonjs': [
      1,
      { allowRequire: true, allowPrimitiveModules: true },
    ],
    'import/no-cycle': 2,
    'import/no-default-export': 1,
    'import/no-deprecated': 0,
    'import/no-duplicates': 2,
    'import/no-dynamic-require': 2,
    'import/no-extraneous-dependencies': 2,
    'import/no-internal-modules': 0,
    'import/no-mutable-exports': 2,
    'import/no-named-as-default': 0,
    'import/no-named-as-default-member': 2,
    'import/no-named-default': 2,
    'import/no-namespace': 0,
    'import/no-nodejs-modules': 0,
    'import/no-relative-parent-imports': 0,
    'import/no-restricted-paths': [
      2,
      { zones: [{ target: './path', from: './path' }] },
    ],
    'import/no-self-import': 2,
    'import/no-unassigned-import': 0,
    'import/no-unresolved': [0, { commonjs: true }],
    'import/no-useless-path-segments': 2,
    'import/no-webpack-loader-syntax': 2,
    'import/order': 2,
    'import/prefer-default-export': 0,
    'import/unambiguous': 0,

    // -- eslint-plugin-unicorn
    'unicorn/catch-error-name': [2, { name: 'error' }],
    'unicorn/explicit-length-check': 2,
    'unicorn/filename-case': 0,
    'unicorn/no-abusive-eslint-disable': 1,
    'unicorn/no-process-exit': 2,
    'unicorn/throw-new-error': 2,
    'unicorn/number-literal-case': 2,
    'unicorn/escape-case': 2,
    'unicorn/no-array-instanceof': 2,
    'unicorn/no-new-buffer': 2,
    'unicorn/no-hex-escape': 2,
    'unicorn/custom-error-definition': 2,
    'unicorn/prefer-exponentiation-operator': 2,
    'unicorn/prefer-starts-ends-with': 2,
    'unicorn/prefer-type-error': 2,
    'unicorn/no-fn-reference-in-iterator': 0,
    'unicorn/import-index': 2,
    'unicorn/new-for-builtins': 2,
    'unicorn/regex-shorthand': 2,
    'unicorn/prefer-spread': 2,
    'unicorn/error-message': 2,
    'unicorn/no-unsafe-regex': 2,
    'unicorn/prefer-add-event-listener': 2,

    // -- eslint-plugin-eslint-comments
    'eslint-comments/disable-enable-pair': 2,
    'eslint-comments/no-aggregating-enable': 2,
    'eslint-comments/no-duplicate-disable.': 0,
    'eslint-comments/no-unlimited-disable': 0,
    'eslint-comments/no-unused-disable': 1,
    'eslint-comments/no-unused-enable': 1,

    // -- eslint-plugin-jest
    'jest/consistent-test-it': [2, { fn: 'test', withinDescribe: 'it' }],
    'jest/expect-expect': 2,
    'jest/lowercase-name': 2,
    'jest/no-disabled-tests': 1,
    'jest/no-focused-tests': 2,
    'jest/prefer-inline-snapshots': 0,
    'jest/no-hooks': 2,
    'jest/no-identical-title': 2,
    'jest/no-jasmine-globals': 2,
    'jest/no-jest-import': 1,
    'jest/no-large-snapshots': [1, { maxSize: 30 }],
    'jest/no-test-prefixes': 2,
    'jest/no-test-return-statement': 2,
    'jest/prefer-expect-assertions': 0,
    'jest/prefer-strict-equal': 1,
    'jest/prefer-to-be-null': 2,
    'jest/prefer-to-be-undefined': 2,
    'jest/prefer-to-have-length': 2,
    'jest/valid-describe': 2,
    'jest/valid-expect-in-promise': 2,
    'jest/valid-expect': 2,

    // -- blacklist rules
    // 'id-blacklist': [2, 'exampleIdentifier'],
    // 'id-length': 0,
    // 'id-match': 0,
    // 'no-restricted-syntax': [2, 'FunctionExpression'],
    // 'eslint-comments/no-restricted-disable': [2, 'example-rule'],
    // "eslint-comments/no-use": ["error", {"allow": []}]
  },
  overrides: [{ files: ['*.config.js'], rules: { 'import/no-commonjs': 0 } }],
  settings: {
    'import/cache': {
      lifetime: 30,
    },
    'import/resolver': {
      node: {
        extensions: ['.js', '.android.js', '.ios.js', '.json'],
      },
    },
  },
};
/* eslint-enable max-lines */
