frozenInstalls: true
initLicense: MIT
initScope: '@meatwallace'
initVersion: '1.0.0-development'
lastUpdateCheck: 1560910052890
npmPublishAccess: public
plugins:
  - .yarn/plugins/@berry/plugin-version.js
  - .yarn/plugins/@berry/plugin-stage.js
  - .yarn/plugins/@berry/plugin-typescript.js
  - .yarn/plugins/@berry/plugin-workspace-tools.js
