// @flow
module.exports = {
  rules: {
    'body-leading-blank': [2, 'always'],
    // 'body-max-length': [0, 'always', Infinity],
    // 'body-max-line-length': [0, 'always', Infinity],
    // 'body-min-length': [0, 'always', 0],
    'footer-leading-blank': [2, 'always'],
    // 'footer-max-length': [0, 'always', Infinity],
    // 'footer-min-length': [0, 'always', 0],
    'header-case': [2, 'always', 'lower-case'],
    'header-full-stop': [2, 'never', '.'],
    'header-max-length': [2, 'always', 72],
    // 'header-min-length': [0, 'always', 0],
    // 'references-empty': [0, 'never'],
    // 'scope-enum': [0, 'always', []],
    'scope-case': [2, 'always', 'lower-case'],
    // 'scope-max-length': [0, 'always', 72],
    // 'scope-min-length': [0, 'always', 0],
    'subject-case': [2, 'always', 'lower-case'],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    // 'subject-max-length': [0, 'always', Infinity],
    // 'subject-min-length': [0, 'always', 0],
    'type-enum': [
      2,
      'always',
      [
        'build',
        'chore',
        'ci',
        'docs',
        'feat',
        'fix',
        'perf',
        'refactor',
        'revert',
        'style',
        'test',
      ],
    ],
    'type-case': [2, 'always', 'lower-case'],
    'type-empty': [2, 'never'],
    // 'typr-max-length': [0, 'always', Infinity],
    // 'type-min-length': [0, 'always', 0],
    // 'signed-off-by': [0, 'always', 'Signed-off-by:'],
  },
};
